#!/usr/bin/env bash
# Interactive production deploy helper for uuBot.
#
# What it does:
# - Downloads a pre-built uuBot binary from a URL you provide.
# - Writes a production .env file from prompts.
# - Installs/updates a systemd service for process supervision.
# - Optionally writes and enables an nginx reverse-proxy config after asking for a domain.
#
# Run on the target server:
#   sudo bash deploy.sh

set -euo pipefail

APP_NAME="uuBot"
APP_USER="uubot"
INSTALL_DIR="/opt/uubot"
BIN_PATH="$INSTALL_DIR/uuBot"
ENV_PATH="$INSTALL_DIR/.env"
SERVICE_PATH="/etc/systemd/system/uubot.service"
NGINX_SITE_PATH="/etc/nginx/sites-available/uubot.conf"
NGINX_SITE_LINK="/etc/nginx/sites-enabled/uubot.conf"
DEFAULT_BIND_ADDR="127.0.0.1:8080"
DEFAULT_DATABASE_URL="sqlite://$INSTALL_DIR/data.db?mode=rwc"
DEFAULT_RELEASE_URL="https://github.com/WangTianYou537/uuBot/releases/latest/download/uuBot"

if [[ "${EUID}" -ne 0 ]]; then
  echo "请用 root 权限运行：sudo bash deploy.sh"
  exit 1
fi

ask() {
  local prompt="$1"
  local default="${2:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " value
    echo "${value:-$default}"
  else
    read -r -p "$prompt: " value
    echo "$value"
  fi
}

ask_secret() {
  local prompt="$1"
  local default="${2:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -s -p "$prompt [留空使用默认值]: " value
    echo >&2
    echo "${value:-$default}"
  else
    read -r -s -p "$prompt: " value
    echo >&2
    echo "$value"
  fi
}

yes_no() {
  local prompt="$1"
  local default="${2:-n}"
  local suffix="[y/N]"
  [[ "$default" == "y" ]] && suffix="[Y/n]"
  local value
  read -r -p "$prompt $suffix: " value
  value="${value:-$default}"
  [[ "$value" =~ ^[Yy]$ ]]
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
  fi
}

install_downloader() {
  if command -v curl >/dev/null 2>&1; then
    DOWNLOADER=(curl -fL --retry 3 -o)
  elif command -v wget >/dev/null 2>&1; then
    DOWNLOADER=(wget -O)
  else
    echo "未找到 curl 或 wget，正在安装 curl..."
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update
      apt-get install -y curl
    elif command -v dnf >/dev/null 2>&1; then
      dnf install -y curl
    elif command -v yum >/dev/null 2>&1; then
      yum install -y curl
    else
      echo "无法自动安装 curl，请先安装 curl 或 wget 后重试。"
      exit 1
    fi
    DOWNLOADER=(curl -fL --retry 3 -o)
  fi
}

ensure_user() {
  if ! id -u "$APP_USER" >/dev/null 2>&1; then
    echo "==> 创建系统用户 $APP_USER"
    useradd --system --home-dir "$INSTALL_DIR" --shell /usr/sbin/nologin "$APP_USER"
  fi
}

prepare_dirs() {
  echo "==> 准备安装目录 $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
  chown -R "$APP_USER:$APP_USER" "$INSTALL_DIR"
}

download_binary() {
  local release_url="$1"
  if [[ -z "$release_url" ]]; then
    echo "必须填写预构建二进制下载 URL。"
    exit 1
  fi

  install_downloader
  local tmp
  tmp="$(mktemp)"
  echo "==> 下载预构建二进制"
  "${DOWNLOADER[@]}" "$tmp" "$release_url"

  install -m 0755 -o "$APP_USER" -g "$APP_USER" "$tmp" "$BIN_PATH"
  rm -f "$tmp"
  echo "==> 已安装二进制到 $BIN_PATH"
}

write_env() {
  echo
  echo "==> 配置 .env"
  local domain="$1"
  local public_default="http://$domain"
  if [[ -z "$domain" ]]; then
    public_default="http://localhost:8080"
  fi

  local database_url bind_addr public_base_url jwt_secret admin_username admin_password cookie_secure
  database_url="$(ask "DATABASE_URL" "$DEFAULT_DATABASE_URL")"
  bind_addr="$(ask "BIND_ADDR" "$DEFAULT_BIND_ADDR")"
  public_base_url="$(ask "PUBLIC_BASE_URL" "$public_default")"
  jwt_secret="$(ask_secret "JWT_SECRET" "$(random_secret)")"
  admin_username="$(ask "ADMIN_USERNAME" "admin")"
  admin_password="$(ask_secret "ADMIN_PASSWORD" "admin123")"
  cookie_secure="$(ask "COOKIE_SECURE (使用 HTTPS 时填 true)" "true")"

  cat >"$ENV_PATH" <<EOF_ENV
# Generated by deploy.sh
DATABASE_URL=$database_url
BIND_ADDR=$bind_addr
PUBLIC_BASE_URL=$public_base_url
JWT_SECRET=$jwt_secret
ADMIN_USERNAME=$admin_username
ADMIN_PASSWORD=$admin_password
COOKIE_SECURE=$cookie_secure
EOF_ENV

  chown "$APP_USER:$APP_USER" "$ENV_PATH"
  chmod 0600 "$ENV_PATH"
  echo "==> 已写入 $ENV_PATH"
}

write_systemd_service() {
  echo "==> 配置 systemd 进程守护"
  cat >"$SERVICE_PATH" <<EOF_SERVICE
[Unit]
Description=uuBot word collection service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$APP_USER
Group=$APP_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$ENV_PATH
ExecStart=$BIN_PATH
Restart=always
RestartSec=3
KillSignal=SIGINT
TimeoutStopSec=20

# Basic hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ReadWritePaths=$INSTALL_DIR

[Install]
WantedBy=multi-user.target
EOF_SERVICE

  systemctl daemon-reload
  systemctl enable uubot.service
  systemctl restart uubot.service
  echo "==> systemd 服务已启动：uubot.service"
}

ensure_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    return 0
  fi

  echo "未检测到 nginx。"
  if ! yes_no "是否安装 nginx？" "y"; then
    return 1
  fi

  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    apt-get install -y nginx
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y nginx
  elif command -v yum >/dev/null 2>&1; then
    yum install -y nginx
  else
    echo "无法自动安装 nginx，请手动安装后重试 nginx 配置。"
    return 1
  fi
}

write_nginx_config() {
  echo
  if ! yes_no "是否复制/写入 nginx 反向代理配置？" "y"; then
    return 0
  fi

  if ! ensure_nginx; then
    echo "跳过 nginx 配置。"
    return 0
  fi

  local domain bind_host bind_port
  domain="$(ask "请输入域名（例如 words.example.com）")"
  if [[ -z "$domain" ]]; then
    echo "域名为空，跳过 nginx 配置。"
    return 0
  fi

  bind_host="127.0.0.1"
  bind_port="8080"

  cat >"$NGINX_SITE_PATH" <<EOF_NGINX
server {
    listen 80;
    server_name $domain;

    client_max_body_size 20m;

    location / {
        proxy_pass http://$bind_host:$bind_port;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF_NGINX

  mkdir -p /etc/nginx/sites-enabled
  ln -sfn "$NGINX_SITE_PATH" "$NGINX_SITE_LINK"

  nginx -t
  systemctl enable nginx
  systemctl reload nginx || systemctl restart nginx
  echo "==> nginx 配置已启用：$NGINX_SITE_PATH"

  DEPLOY_DOMAIN="$domain"
}

main() {
  echo "uuBot 部署脚本"
  echo "============="
  echo

  local release_url deploy_domain
  release_url="$(ask "请输入预构建 uuBot 二进制下载 URL" "$DEFAULT_RELEASE_URL")"

  ensure_user
  prepare_dirs
  download_binary "$release_url"

  DEPLOY_DOMAIN=""
  write_nginx_config
  deploy_domain="$DEPLOY_DOMAIN"

  write_env "$deploy_domain"
  write_systemd_service

  echo
  echo "部署完成。"
  echo "常用命令："
  echo "  systemctl status uubot --no-pager"
  echo "  journalctl -u uubot -f"
  echo "  systemctl restart uubot"
  if [[ -n "$deploy_domain" ]]; then
    echo
    echo "站点地址：http://$deploy_domain"
    echo "如需 HTTPS，建议运行：certbot --nginx -d $deploy_domain"
  fi
}

main "$@"
